In [1]:
from pydataset import data

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(123)

In [4]:
students = ['Sally', 'Jane', 'Suzie', 'Billy', 'Ada', 'John', 'Thomas',
            'Marie', 'Albert', 'Richard', 'Isaac', 'Alan']

In [5]:
math_grades = np.random.randint(low=60, high=100, size=len(students))
english_grades = np.random.randint(low=60, high=100, size=len(students))
reading_grades = np.random.randint(low=60, high=100, size=len(students))

In [6]:
df = pd.DataFrame({'name': students,
                   'math': math_grades,
                   'english': english_grades,
                   'reading': reading_grades})

In [17]:
df

       name  math  english  reading  passing_english
0     Sally    62       85       80             True
1      Jane    88       79       67             True
2     Suzie    94       74       95             True
3     Billy    98       96       88             True
4       Ada    77       92       98             True
5      John    79       76       93             True
6    Thomas    82       64       81            False
7     Marie    93       63       90            False
8    Albert    92       62       87            False
9   Richard    69       80       94             True
10    Isaac    92       99       93             True
11     Alan    92       62       72            False

In [8]:
# Create a column named passing_english that indicates whether each student has a passing grade in reading.
df["passing_english"] = df['english'] > 69

In [9]:
# Sort the english grades by the passing_english column. How are duplicates handled?
df.sort_values(by=["passing_english","name"])
# Duplicates are sorted by the row-index in ascending order

       name  math  english  reading  passing_english
11     Alan    92       62       72            False
8    Albert    92       62       87            False
7     Marie    93       63       90            False
6    Thomas    82       64       81            False
4       Ada    77       92       98             True
3     Billy    98       96       88             True
10    Isaac    92       99       93             True
1      Jane    88       79       67             True
5      John    79       76       93             True
9   Richard    69       80       94             True
0     Sally    62       85       80             True
2     Suzie    94       74       95             True

In [21]:
# Sort the english grades first by passing_english and then by student name. All the students
# that are failing english should be first, and within the students that are failing english 
# they should be ordered alphabetically. The same should be true for the students passing 
# english. (Hint: you can pass a list to the .sort_values method)
df.sort_values(by=["passing_english","name"])

       name  math  english  reading  passing_english
11     Alan    92       62       72            False
8    Albert    92       62       87            False
7     Marie    93       63       90            False
6    Thomas    82       64       81            False
4       Ada    77       92       98             True
3     Billy    98       96       88             True
10    Isaac    92       99       93             True
1      Jane    88       79       67             True
5      John    79       76       93             True
9   Richard    69       80       94             True
0     Sally    62       85       80             True
2     Suzie    94       74       95             True

In [22]:
# Sort the english grades first by passing_english, and then by the actual english grade, similar to how we did in the last step.
df.sort_values(by=["passing_english","english"])

       name  math  english  reading  passing_english
8    Albert    92       62       87            False
11     Alan    92       62       72            False
7     Marie    93       63       90            False
6    Thomas    82       64       81            False
2     Suzie    94       74       95             True
5      John    79       76       93             True
1      Jane    88       79       67             True
9   Richard    69       80       94             True
0     Sally    62       85       80             True
4       Ada    77       92       98             True
3     Billy    98       96       88             True
10    Isaac    92       99       93             True

In [23]:
df

       name  math  english  reading  passing_english
0     Sally    62       85       80             True
1      Jane    88       79       67             True
2     Suzie    94       74       95             True
3     Billy    98       96       88             True
4       Ada    77       92       98             True
5      John    79       76       93             True
6    Thomas    82       64       81            False
7     Marie    93       63       90            False
8    Albert    92       62       87            False
9   Richard    69       80       94             True
10    Isaac    92       99       93             True
11     Alan    92       62       72            False

In [24]:
# Calculate each students overall grade and add it as a column on the dataframe. 
# The overall grade is the average of the math, english, and reading grades.

#this sums all the values in each row.
#the sum collapses all the fields into one field per row.
#I'll add this as a column
df.sum(axis=1)

0     228.0
1     235.0
2     264.0
3     283.0
4     268.0
5     249.0
6     227.0
7     246.0
8     241.0
9     244.0
10    285.0
11    226.0
dtype: float64

In [26]:
df['overall_grade'] = df.sum(axis=1)

In [28]:
df.sort_values(by='overall_grade')

       name  math  english  reading  passing_english  overall_grade
11     Alan    92       62       72            False          226.0
6    Thomas    82       64       81            False          227.0
0     Sally    62       85       80             True          228.0
1      Jane    88       79       67             True          235.0
8    Albert    92       62       87            False          241.0
9   Richard    69       80       94             True          244.0
7     Marie    93       63       90            False          246.0
5      John    79       76       93             True          249.0
2     Suzie    94       74       95             True          264.0
4       Ada    77       92       98             True          268.0
3     Billy    98       96       88             True          283.0
10    Isaac    92       99       93             True          285.0

In [11]:
mpg = data('mpg')

In [34]:
# 2
# How many rows and columns are there?
print(f"There are {mpg.shape[0]} rows and {mpg.shape[1]} columns.")

There are 234 rows and 11 columns.

In [37]:
# What are the data types of each column?
mpg.dtypes

manufacturer     object
model            object
displ           float64
year              int64
cyl               int64
trans            object
drv              object
cty               int64
hwy               int64
fl               object
class            object
dtype: object

In [18]:
#messing around to see the dtypes are a Series object. 
mpg.dtypes[:'year']
mpg.dtypes.iloc[:4]

manufacturer     object
model            object
displ           float64
year              int64
dtype: object

In [19]:
mpg.dtypes[:'year']

manufacturer     object
model            object
displ           float64
year              int64
dtype: object

In [42]:
# Summarize the dataframe with .info and .describe
# mpg.describe
# mpg.info

In [23]:
# Rename the cty column to city.
mpg = mpg.rename(columns={"cty": "city"})
mpg.head(10)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
6,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
8,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
9,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
10,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact

In [21]:
# Rename the hwy column to highway.
mpg = mpg.rename(columns={"hwy": "highway"})
# I could've done that on the last cell if I knew I was gonna rename two columns. =(

In [24]:
# Do any cars have better city mileage than highway mileage?
mpg[mpg['city'] > mpg['highway']]
#That boolean mask returned no rows. So I'd say no.

Empty DataFrame
Columns: [manufacturer, model, displ, year, cyl, trans, drv, city, highway, fl, class]
Index: []

In [26]:
# Create a column named mileage_difference this column should contain the difference 
# between highway and city mileage for each car.
mpg['mileage_difference'] = mpg['highway'] - mpg['city']
mpg.sort_values(by='mileage_difference', ascending=False)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference
107,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact,12
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,12
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,11
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize,11
36,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize,11
213,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,11
106,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact,11
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,11
24,chevrolet,corvette,5.7,1999,8,manual(m6),r,16,26,p,2seater,10
183,toyota,camry,2.4,2008,4,auto(l5),f,21,31,r,midsize,10
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,10
112,hyundai,sonata,2.4,2008,4,manual(m5),f,21,31,r,midsize,10
117,hyundai,tiburon,2.0,1999,4,manual(m5),f,19,29,r,subcompact,10
156,pontiac,grand prix,3.8,1999,6,auto(l4),f,16,26,p,midsize,10
157,pontiac,grand prix,3.8,1999,6,auto(l4),f,17,27,r,midsize,10
158,pontiac,grand prix,3.8,2008,6,auto(l4),f,18,28,r,midsize,10
27,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater,10
26,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater,10
182,toyota,camry,2.4,2008,4,manual(m5),f,21,31,r,midsize,10
189,toyota,camry solara,2.4,2008,4,manual(m5),f,21,31,r,compact,10
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,10
12,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact,10
15,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact,10
186,toyota,camry,3.5,2008,6,auto(s6),f,19,28,r,midsize,9
145,nissan,altima,2.5,2008,4,manual(m6),f,23,32,r,midsize,9
222,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact,9
110,hyundai,sonata,2.4,1999,4,manual(m5),f,18,27,r,midsize,9
111,hyundai,sonata,2.4,2008,4,auto(l4),f,21,30,r,midsize,9
115,hyundai,sonata,3.3,2008,6,auto(l5),f,19,28,r,midsize,9
198,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact,9
197,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact,9
93,ford,mustang,4.0,2008,6,manual(m5),r,17,26,r,subcompact,9
196,toyota,corolla,1.8,1999,4,manual(m5),f,26,35,r,compact,9
195,toyota,corolla,1.8,1999,4,auto(l4),f,24,33,r,compact,9
193,toyota,camry solara,3.3,2008,6,auto(s5),f,18,27,r,compact,9
159,pontiac,grand prix,5.3,2008,8,auto(s4),f,16,25,p,midsize,9
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,9
190,toyota,camry solara,2.4,2008,4,auto(s5),f,22,31,r,compact,9
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact,9
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,9
9,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact,9
16,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize,9
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,9
37,chevrolet,malibu,3.6,2008,6,auto(s6),f,17,26,r,midsize,9
28,chevrolet,corvette,7.0,2008,8,manual(m6),r,15,24,p,2seater,9
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact,9
191,toyota,camry solara,3.0,1999,6,auto(l4),f,18,26,r,compact,8
184,toyota,camry,3.0,1999,6,auto(l4),f,18,26,r,midsize,8
185,toyota,camry,3.0,1999,6,manual(m5),f,18,26,r,midsize,8
188,toyota,camry solara,2.2,1999,4,manual(m5),f,21,29,r,compact,8
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,8
118,hyundai,tiburon,2.0,2008,4,manual(m5),f,20,28,r,subcompact,8
33,chevrolet,malibu,2.4,1999,4,auto(l4),f,19,27,r,midsize,8
17,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize,8
14,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact,8
13,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact,8
192,toyota,camry solara,3.0,1999,6,manual(m5),f,18,26,r,compact,8
180,toyota,camry,2.2,1999,4,manual(m5),f,21,29,r,midsize,8
104,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,8
114,hyundai,sonata,2.5,1999,6,manual(m5),f,18,26,r,midsize,8
113,hyundai,sonata,2.5,1999,6,auto(l4),f,18,26,r,midsize,8
91,ford,mustang,3.8,1999,6,manual(m5),r,18,26,r,subcompact,8
34,chevrolet,malibu,2.4,2008,4,auto(l4),f,22,30,r,midsize,8
35,chevrolet,malibu,3.1,1999,6,auto(l4),f,18,26,r,midsize,8
94,ford,mustang,4.0,2008,6,auto(l5),r,16,24,r,subcompact,8
109,hyundai,sonata,2.4,1999,4,auto(l4),f,18,26,r,midsize,8
97,ford,mustang,4.6,2008,8,manual(m5),r,15,23,r,subcompact,8
108,honda,civic,2.0,2008,4,manual(m6),f,21,29,p,subcompact,8
105,honda,civic,1.8,2008,4,manual(m5),f,26,34,r,subcompact,8
208,volkswagen,gti,2.0,1999,4,manual(m5),f,21,29,r,compact,8
121,hyundai,tiburon,2.7,2008,6,manual(m6),f,16,24,r,subcompact,8
210,volkswagen,gti,2.0,2008,4,manual(m6),f,21,29,p,compact,8
148,nissan,maxima,3.0,1999,6,auto(l4),f,18,26,r,midsize,8
142,nissan,altima,2.4,1999,4,manual(m5),f,21,29,r,compact,8
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,8
143,nissan,altima,2.4,1999,4,auto(l4),f,19,27,r,compact,8
144,nissan,altima,2.5,2008,4,auto(av),f,23,31,r,midsize,8
146,nissan,altima,3.5,2008,6,manual(m6),f,19,27,p,midsize,8
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,8
6,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact,8
228,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize,8
8,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact,8
226,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact,8
224,volkswagen,new beetle,2.0,1999,4,manual(m5),f,21,29,r,subcompact,8
10,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact,8
...,...,...,...,...,...,...,...,...,...,...,...,...
99,ford,mustang,5.4,2008,8,manual(m6),r,14,20,p,subcompact,6
75,ford,expedition 2wd,4.6,1999,8,auto(l4),r,11,17,r,suv,6
137,lincoln,navigator 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv,6
46,dodge,caravan 2wd,3.8,1999,6,auto(l4),f,15,21,r,minivan,6
135,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv,6
132,land rover,range rover,4.2,2008,8,auto(s6),4,12,18,r,suv,6
44,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,11,17,e,minivan,6
133,land rover,range rover,4.4,2008,8,auto(s6),4,12,18,r,suv,6
63,dodge,durango 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,5
62,dodge,durango 4wd,5.2,1999,8,auto(l4),4,11,16,r,suv,5
53,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,5
203,toyota,toyota tacoma 4wd,2.7,2008,4,manual(m5),4,17,22,r,pickup,5
23,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv,5
72,dodge,ram 1500 pickup 4wd,5.2,1999,8,manual(m5),4,11,16,r,pickup,5
201,toyota,toyota tacoma 4wd,2.7,1999,4,manual(m5),4,15,20,r,pickup,5
200,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv,5
136,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,16,p,suv,5
170,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,25,p,compact,5
174,toyota,4runner 4wd,2.7,1999,4,manual(m5),4,15,20,r,suv,5
166,subaru,impreza awd,2.2,1999,4,auto(l4),4,21,26,r,subcompact,5
129,jeep,grand cherokee 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,5
165,subaru,forester awd,2.5,2008,4,auto(l4),4,18,23,p,suv,5
128,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,14,19,r,suv,5
54,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,5
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv,5
123,jeep,grand cherokee 4wd,3.0,2008,6,auto(l5),4,17,22,d,suv,5
100,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact,5
125,jeep,grand cherokee 4wd,4.0,1999,6,auto(l4),4,15,20,r,suv,5
74,dodge,ram 1500 pickup 4wd,5.9,1999,8,auto(l4),4,11,15,r,pickup,4
205,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup,4
73,dodge,ram 1500 pickup 4wd,5.7,2008,8,auto(l5),4,13,17,r,pickup,4
199,toyota,land cruiser wagon 4wd,4.7,1999,8,auto(l4),4,11,15,r,suv,4
50,dodge,dakota pickup 4wd,3.7,2008,6,auto(l4),4,14,18,r,pickup,4
57,dodge,dakota pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,4
202,toyota,toyota tacoma 4wd,2.7,1999,4,auto(l4),4,16,20,r,pickup,4
58,dodge,durango 4wd,3.9,1999,6,auto(l4),4,13,17,r,suv,4
207,toyota,toyota tacoma 4wd,4.0,2008,6,auto(l5),4,16,20,r,pickup,4
71,dodge,ram 1500 pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,4
69,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup,4
68,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,4
67,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,4
65,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup,4
64,dodge,durango 4wd,5.9,1999,8,auto(l4),4,11,15,r,suv,4
59,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,4
49,dodge,dakota pickup 4wd,3.7,2008,6,manual(m6),4,15,19,r,pickup,4
61,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,4
51,dodge,dakota pickup 4wd,3.9,1999,6,auto(l4),4,13,17,r,pickup,4
83,ford,explorer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,4
176,toyota,4runner 4wd,3.4,1999,6,auto(l4),4,15,19,r,suv,4
22,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv,4
89,ford,f150 pickup 4wd,5.4,1999,8,auto(l4),4,11,15,r,pickup,4
175,toyota,4runner 4wd,2.7,1999,4,auto(l4),4,16,20,r,suv,4
79,ford,explorer 4wd,4.0,1999,6,manual(m5),4,15,19,r,suv,4
124,jeep,grand cherokee 4wd,3.7,2008,6,auto(l5),4,15,19,r,suv,4
178,toyota,4runner 4wd,4.0,2008,6,auto(l5),4,16,20,r,suv,4
88,ford,f150 pickup 4wd,4.6,2008,8,auto(l4),4,13,17,r,pickup,4
90,ford,f150 pickup 4wd,5.4,2008,8,auto(l4),4,13,17,r,pickup,4
131,land rover,range rover,4.0,1999,8,auto(l4),4,11,15,p,suv,4
134,land rover,range rover,4.6,1999,8,auto(l4),4,11,15,p,suv,4
141,mercury,mountaineer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,4
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv,4
31,chevrolet,k1500 tahoe 4wd,5.7,1999,8,auto(l4),4,11,15,r,suv,4
52,dodge,dakota pickup 4wd,3.9,1999,6,manual(m5),4,14,17,r,pickup,3
151,nissan,pathfinder 4wd,3.3,1999,6,auto(l4),4,14,17,r,suv,3
32,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv,3
55,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3
130,jeep,grand cherokee 4wd,6.1,2008,8,auto(l5),4,11,14,p,suv,3
30,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv,3
126,jeep,grand cherokee 4wd,4.7,1999,8,auto(l4),4,14,17,r,suv,3
127,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,3
78,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3
60,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,3
66,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3
179,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv,3
70,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup,3
87,ford,f150 pickup 4wd,4.6,1999,8,auto(l4),4,13,16,r,pickup,3
86,ford,f150 pickup 4wd,4.6,1999,8,manual(m5),4,13,16,r,pickup,3
206,toyota,toyota tacoma 4wd,4.0,2008,6,manual(m6),4,15,18,r,pickup,3
85,ford,f150 pickup 4wd,4.2,1999,6,manual(m5),4,14,17,r,pickup,3
84,ford,f150 pickup 4wd,4.2,1999,6,auto(l4),4,14,17,r,pickup,3
80,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3
138,mercury,mountaineer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3
177,toyota,4runner 4wd,3.4,1999,6,manual(m5),4,15,17,r,suv,2
152,nissan,pathfinder 4wd,3.3,1999,6,manual(m5),4,15,17,r,suv,2
204,toyota,toyota tacoma 4wd,3.4,1999,6,manual(m5),4,15,17,r,pickup,2

In [54]:
# Which car (or cars) has the highest mileage difference?

#Sorted the cars by the indicated column, from greatest to least, and just the top 5
mpg.sort_values(by="mileage_difference", ascending=False).head(5)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference
107,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact,12
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,12
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,11
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize,11
36,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize,11

In [59]:
# Which compact class car has the lowest highway mileage? 
mpg[mpg['class'] == 'compact'].sort_values(by='highway').head(1)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference
220,volkswagen,jetta,2.8,1999,6,auto(l4),f,16,23,r,compact,7

In [60]:
# The best?
mpg[mpg['class'] == 'compact'].sort_values(by='highway', ascending=False).head(1)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference
213,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,11

In [30]:
(mpg['city'] + mpg['highway'])/2

1      23.5
2      25.0
3      25.5
4      25.5
5      21.0
6      22.0
7      22.5
8      22.0
9      20.5
10     24.0
11     23.0
12     20.0
13     21.0
14     21.0
15     20.0
16     19.5
17     21.0
18     19.5
19     17.0
20     13.0
21     17.0
22     15.0
23     14.5
24     21.0
25     19.0
26     21.0
27     20.0
28     19.5
29     16.5
30     12.5
31     13.0
32     15.5
33     23.0
34     26.0
35     22.0
36     23.5
37     21.5
38     21.0
39     20.5
40     19.0
41     19.0
42     20.5
43     20.5
44     14.0
45     18.5
46     18.0
47     19.5
48     19.5
49     17.0
50     16.0
51     15.0
52     15.5
53     16.5
54     16.5
55     10.5
56     14.0
57     13.0
58     15.0
59     15.0
60     10.5
61     15.0
62     13.5
63     15.5
64     13.0
65     14.0
66     10.5
67     15.0
68     15.0
69     14.0
70     10.5
71     13.0
72     13.5
73     15.0
74     13.0
75     14.0
76     14.0
77     15.0
78     15.5
79     17.0
80     15.5
81     16.0
82     16.0
83     15.0
84     15.5
85     15.5
       ...
150    22.0
151    15.5
152    16.0
153    17.0
154    15.0
155    22.0
156    21.0
157    22.0
158    23.0
159    20.5
160    21.5
161    21.0
162    23.5
163    22.0
164    23.0
165    20.5
166    23.5
167    22.5
168    22.5
169    22.5
170    22.5
171    23.5
172    22.0
173    23.5
174    17.5
175    18.0
176    17.0
177    16.0
178    18.0
179    15.5
180    25.0
181    24.0
182    26.0
183    26.0
184    22.0
185    22.0
186    23.5
187    24.0
188    25.0
189    26.0
190    26.5
191    22.0
192    22.0
193    22.5
194    27.0
195    28.5
196    30.5
197    32.5
198    30.5
199    13.0
200    15.5
201    17.5
202    18.0
203    19.5
204    16.0
205    17.0
206    16.5
207    18.0
208    25.0
209    22.5
210    25.0
211    25.5
212    20.5
213    38.5
214    25.0
215    22.5
216    25.5
217    25.0
218    25.0
219    25.0
220    19.5
221    20.5
222    39.5
223    35.0
224    25.0
225    22.5
226    24.0
227    24.5
228    25.0
229    23.5
230    23.5
231    25.0
232    21.0
233    22.0
234    21.5
Length: 234, dtype: float64

In [31]:
# Create a column named average_mileage that is the mean of the city and highway mileage.
mpg['average_mileage'] = (mpg['city'] + mpg['highway']) / 2
mpg.sort_values(by='average_mileage', ascending=False)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference,average_mileage
222,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact,9,39.5
213,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact,11,38.5
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact,12,35.0
197,toyota,corolla,1.8,2008,4,manual(m5),f,28,37,r,compact,9,32.5
196,toyota,corolla,1.8,1999,4,manual(m5),f,26,35,r,compact,9,30.5
106,honda,civic,1.8,2008,4,auto(l5),f,25,36,r,subcompact,11,30.5
100,honda,civic,1.6,1999,4,manual(m5),f,28,33,r,subcompact,5,30.5
198,toyota,corolla,1.8,2008,4,auto(l4),f,26,35,r,compact,9,30.5
105,honda,civic,1.8,2008,4,manual(m5),f,26,34,r,subcompact,8,30.0
107,honda,civic,1.8,2008,4,auto(l5),f,24,36,c,subcompact,12,30.0
102,honda,civic,1.6,1999,4,manual(m5),f,25,32,r,subcompact,7,28.5
195,toyota,corolla,1.8,1999,4,auto(l4),f,24,33,r,compact,9,28.5
101,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,8,28.0
104,honda,civic,1.6,1999,4,auto(l4),f,24,32,r,subcompact,8,28.0
145,nissan,altima,2.5,2008,4,manual(m6),f,23,32,r,midsize,9,27.5
144,nissan,altima,2.5,2008,4,auto(av),f,23,31,r,midsize,8,27.0
194,toyota,corolla,1.8,1999,4,auto(l3),f,24,30,r,compact,6,27.0
190,toyota,camry solara,2.4,2008,4,auto(s5),f,22,31,r,compact,9,26.5
183,toyota,camry,2.4,2008,4,auto(l5),f,21,31,r,midsize,10,26.0
34,chevrolet,malibu,2.4,2008,4,auto(l4),f,22,30,r,midsize,8,26.0
112,hyundai,sonata,2.4,2008,4,manual(m5),f,21,31,r,midsize,10,26.0
103,honda,civic,1.6,1999,4,manual(m5),f,23,29,p,subcompact,6,26.0
182,toyota,camry,2.4,2008,4,manual(m5),f,21,31,r,midsize,10,26.0
189,toyota,camry solara,2.4,2008,4,manual(m5),f,21,31,r,compact,10,26.0
211,volkswagen,gti,2.0,2008,4,auto(s6),f,22,29,p,compact,7,25.5
216,volkswagen,jetta,2.0,2008,4,auto(s6),f,22,29,p,compact,7,25.5
111,hyundai,sonata,2.4,2008,4,auto(l4),f,21,30,r,midsize,9,25.5
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,11,25.5
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,9,25.5
208,volkswagen,gti,2.0,1999,4,manual(m5),f,21,29,r,compact,8,25.0
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,8,25.0
210,volkswagen,gti,2.0,2008,4,manual(m6),f,21,29,p,compact,8,25.0
108,honda,civic,2.0,2008,4,manual(m6),f,21,29,p,subcompact,8,25.0
228,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize,8,25.0
180,toyota,camry,2.2,1999,4,manual(m5),f,21,29,r,midsize,8,25.0
219,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact,8,25.0
224,volkswagen,new beetle,2.0,1999,4,manual(m5),f,21,29,r,subcompact,8,25.0
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,8,25.0
218,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact,8,25.0
188,toyota,camry solara,2.2,1999,4,manual(m5),f,21,29,r,compact,8,25.0
217,volkswagen,jetta,2.0,2008,4,manual(m6),f,21,29,p,compact,8,25.0
214,volkswagen,jetta,2.0,1999,4,manual(m5),f,21,29,r,compact,8,25.0
142,nissan,altima,2.4,1999,4,manual(m5),f,21,29,r,compact,8,25.0
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact,9,24.5
117,hyundai,tiburon,2.0,1999,4,manual(m5),f,19,29,r,subcompact,10,24.0
118,hyundai,tiburon,2.0,2008,4,manual(m5),f,20,28,r,subcompact,8,24.0
10,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact,8,24.0
226,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact,8,24.0
181,toyota,camry,2.2,1999,4,auto(l4),f,21,27,r,midsize,6,24.0
187,toyota,camry solara,2.2,1999,4,auto(l4),f,21,27,r,compact,6,24.0
119,hyundai,tiburon,2.0,2008,4,auto(l4),f,20,27,r,subcompact,7,23.5
115,hyundai,sonata,3.3,2008,6,auto(l5),f,19,28,r,midsize,9,23.5
166,subaru,impreza awd,2.2,1999,4,auto(l4),4,21,26,r,subcompact,5,23.5
171,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,27,r,compact,7,23.5
173,subaru,impreza awd,2.5,2008,4,manual(m5),4,20,27,r,compact,7,23.5
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize,11,23.5
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,9,23.5
186,toyota,camry,3.5,2008,6,auto(s6),f,19,28,r,midsize,9,23.5
162,subaru,forester awd,2.5,2008,4,manual(m5),4,20,27,r,suv,7,23.5
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,11,23.5
36,chevrolet,malibu,3.5,2008,6,auto(l4),f,18,29,r,midsize,11,23.5
33,chevrolet,malibu,2.4,1999,4,auto(l4),f,19,27,r,midsize,8,23.0
143,nissan,altima,2.4,1999,4,auto(l4),f,19,27,r,compact,8,23.0
146,nissan,altima,3.5,2008,6,manual(m6),f,19,27,p,midsize,8,23.0
11,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact,8,23.0
158,pontiac,grand prix,3.8,2008,6,auto(l4),f,18,28,r,midsize,10,23.0
164,subaru,forester awd,2.5,2008,4,auto(l4),4,20,26,r,suv,6,23.0
170,subaru,impreza awd,2.5,2008,4,auto(s4),4,20,25,p,compact,5,22.5
116,hyundai,tiburon,2.0,1999,4,auto(l4),f,19,26,r,subcompact,7,22.5
147,nissan,altima,3.5,2008,6,auto(av),f,19,26,p,midsize,7,22.5
167,subaru,impreza awd,2.2,1999,4,manual(m5),4,19,26,r,subcompact,7,22.5
168,subaru,impreza awd,2.5,1999,4,manual(m5),4,19,26,r,subcompact,7,22.5
169,subaru,impreza awd,2.5,1999,4,auto(l4),4,19,26,r,subcompact,7,22.5
110,hyundai,sonata,2.4,1999,4,manual(m5),f,18,27,r,midsize,9,22.5
225,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact,7,22.5
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact,9,22.5
193,toyota,camry solara,3.3,2008,6,auto(s5),f,18,27,r,compact,9,22.5
209,volkswagen,gti,2.0,1999,4,auto(l4),f,19,26,r,compact,7,22.5
215,volkswagen,jetta,2.0,1999,4,auto(l4),f,19,26,r,compact,7,22.5
155,pontiac,grand prix,3.1,1999,6,auto(l4),f,18,26,r,midsize,8,22.0
113,hyundai,sonata,2.5,1999,6,auto(l4),f,18,26,r,midsize,8,22.0
114,hyundai,sonata,2.5,1999,6,manual(m5),f,18,26,r,midsize,8,22.0
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,8,22.0
6,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact,8,22.0
8,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact,8,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,toyota,4runner 4wd,2.7,1999,4,manual(m5),4,15,20,r,suv,5,17.5
125,jeep,grand cherokee 4wd,4.0,1999,6,auto(l4),4,15,20,r,suv,5,17.5
201,toyota,toyota tacoma 4wd,2.7,1999,4,manual(m5),4,15,20,r,pickup,5,17.5
176,toyota,4runner 4wd,3.4,1999,6,auto(l4),4,15,19,r,suv,4,17.0
99,ford,mustang,5.4,2008,8,manual(m6),r,14,20,p,subcompact,6,17.0
124,jeep,grand cherokee 4wd,3.7,2008,6,auto(l5),4,15,19,r,suv,4,17.0
49,dodge,dakota pickup 4wd,3.7,2008,6,manual(m6),4,15,19,r,pickup,4,17.0
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv,6,17.0
21,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv,6,17.0
153,nissan,pathfinder 4wd,4.0,2008,6,auto(l5),4,14,20,p,suv,6,17.0
79,ford,explorer 4wd,4.0,1999,6,manual(m5),4,15,19,r,suv,4,17.0
205,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup,4,17.0
54,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,5,16.5
53,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,14,19,r,pickup,5,16.5
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv,5,16.5
128,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,14,19,r,suv,5,16.5
206,toyota,toyota tacoma 4wd,4.0,2008,6,manual(m6),4,15,18,r,pickup,3,16.5
177,toyota,4runner 4wd,3.4,1999,6,manual(m5),4,15,17,r,suv,2,16.0
152,nissan,pathfinder 4wd,3.3,1999,6,manual(m5),4,15,17,r,suv,2,16.0
82,ford,explorer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv,6,16.0
81,ford,explorer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv,6,16.0
204,toyota,toyota tacoma 4wd,3.4,1999,6,manual(m5),4,15,17,r,pickup,2,16.0
50,dodge,dakota pickup 4wd,3.7,2008,6,auto(l4),4,14,18,r,pickup,4,16.0
139,mercury,mountaineer 4wd,4.0,2008,6,auto(l5),4,13,19,r,suv,6,16.0
140,mercury,mountaineer 4wd,4.6,2008,8,auto(l6),4,13,19,r,suv,6,16.0
32,chevrolet,k1500 tahoe 4wd,6.5,1999,8,auto(l4),4,14,17,d,suv,3,15.5
138,mercury,mountaineer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3,15.5
200,toyota,land cruiser wagon 4wd,5.7,2008,8,auto(s6),4,13,18,r,suv,5,15.5
78,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3,15.5
151,nissan,pathfinder 4wd,3.3,1999,6,auto(l4),4,14,17,r,suv,3,15.5
179,toyota,4runner 4wd,4.7,2008,8,auto(l5),4,14,17,r,suv,3,15.5
84,ford,f150 pickup 4wd,4.2,1999,6,auto(l4),4,14,17,r,pickup,3,15.5
63,dodge,durango 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,5,15.5
129,jeep,grand cherokee 4wd,5.7,2008,8,auto(l5),4,13,18,r,suv,5,15.5
52,dodge,dakota pickup 4wd,3.9,1999,6,manual(m5),4,14,17,r,pickup,3,15.5
80,ford,explorer 4wd,4.0,1999,6,auto(l5),4,14,17,r,suv,3,15.5
85,ford,f150 pickup 4wd,4.2,1999,6,manual(m5),4,14,17,r,pickup,3,15.5
126,jeep,grand cherokee 4wd,4.7,1999,8,auto(l4),4,14,17,r,suv,3,15.5
68,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,4,15.0
67,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,13,17,r,pickup,4,15.0
22,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv,4,15.0
58,dodge,durango 4wd,3.9,1999,6,auto(l4),4,13,17,r,suv,4,15.0
83,ford,explorer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,4,15.0
61,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,4,15.0
132,land rover,range rover,4.2,2008,8,auto(s6),4,12,18,r,suv,6,15.0
90,ford,f150 pickup 4wd,5.4,2008,8,auto(l4),4,13,17,r,pickup,4,15.0
141,mercury,mountaineer 4wd,5.0,1999,8,auto(l4),4,13,17,r,suv,4,15.0
137,lincoln,navigator 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv,6,15.0
88,ford,f150 pickup 4wd,4.6,2008,8,auto(l4),4,13,17,r,pickup,4,15.0
133,land rover,range rover,4.4,2008,8,auto(s6),4,12,18,r,suv,6,15.0
77,ford,expedition 2wd,5.4,2008,8,auto(l6),r,12,18,r,suv,6,15.0
51,dodge,dakota pickup 4wd,3.9,1999,6,auto(l4),4,13,17,r,pickup,4,15.0
59,dodge,durango 4wd,4.7,2008,8,auto(l5),4,13,17,r,suv,4,15.0
73,dodge,ram 1500 pickup 4wd,5.7,2008,8,auto(l5),4,13,17,r,pickup,4,15.0
154,nissan,pathfinder 4wd,5.6,2008,8,auto(s5),4,12,18,p,suv,6,15.0
86,ford,f150 pickup 4wd,4.6,1999,8,manual(m5),4,13,16,r,pickup,3,14.5
87,ford,f150 pickup 4wd,4.6,1999,8,auto(l4),4,13,16,r,pickup,3,14.5
23,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv,5,14.5
69,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup,4,14.0
135,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv,6,14.0
65,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,12,16,r,pickup,4,14.0
56,dodge,dakota pickup 4wd,5.2,1999,8,manual(m5),4,11,17,r,pickup,6,14.0
44,dodge,caravan 2wd,3.3,2008,6,auto(l4),f,11,17,e,minivan,6,14.0
76,ford,expedition 2wd,5.4,1999,8,auto(l4),r,11,17,r,suv,6,14.0
75,ford,expedition 2wd,4.6,1999,8,auto(l4),r,11,17,r,suv,6,14.0
72,dodge,ram 1500 pickup 4wd,5.2,1999,8,manual(m5),4,11,16,r,pickup,5,13.5
62,dodge,durango 4wd,5.2,1999,8,auto(l4),4,11,16,r,suv,5,13.5
136,lincoln,navigator 2wd,5.4,1999,8,auto(l4),r,11,16,p,suv,5,13.5
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv,4,13.0
31,chevrolet,k1500 tahoe 4wd,5.7,1999,8,auto(l4),4,11,15,r,suv,4,13.0
64,dodge,durango 4wd,5.9,1999,8,auto(l4),4,11,15,r,suv,4,13.0
74,dodge,ram 1500 pickup 4wd,5.9,1999,8,auto(l4),4,11,15,r,pickup,4,13.0
199,toyota,land cruiser wagon 4wd,4.7,1999,8,auto(l4),4,11,15,r,suv,4,13.0
71,dodge,ram 1500 pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,4,13.0
131,land rover,range rover,4.0,1999,8,auto(l4),4,11,15,p,suv,4,13.0
134,land rover,range rover,4.6,1999,8,auto(l4),4,11,15,p,suv,4,13.0
57,dodge,dakota pickup 4wd,5.2,1999,8,auto(l4),4,11,15,r,pickup,4,13.0
89,ford,f150 pickup 4wd,5.4,1999,8,auto(l4),4,11,15,r,pickup,4,13.0
30,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv,3,12.5
130,jeep,grand cherokee 4wd,6.1,2008,8,auto(l5),4,11,14,p,suv,3,12.5
127,jeep,grand cherokee 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,3,10.5
60,dodge,durango 4wd,4.7,2008,8,auto(l5),4,9,12,e,suv,3,10.5
66,dodge,ram 1500 pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3,10.5
70,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup,3,10.5
55,dodge,dakota pickup 4wd,4.7,2008,8,auto(l5),4,9,12,e,pickup,3,10.5

In [72]:
# Which dodge car has the best average mileage? 
mpg[mpg['manufacturer'] == 'dodge'].sort_values(by="average_mileage", ascending=False).head(1)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference,average_mileage
38,dodge,caravan 2wd,2.4,1999,4,auto(l3),f,18,24,r,minivan,6,30.0

In [32]:
# The worst?
mpg[mpg['manufacturer'] == 'dodge'].sort_values(by="average_mileage").head(1)

,manufacturer,model,displ,year,cyl,trans,drv,city,highway,fl,class,mileage_difference,average_mileage
70,dodge,ram 1500 pickup 4wd,4.7,2008,8,manual(m6),4,9,12,e,pickup,3,10.5

In [ ]:
#3
#mammals dataset

In [33]:
mammals = data('Mammals')

In [79]:
# How many rows and columns are there?
mammals.shape
print(f"There are {mammals.shape[0]} rows and {mammals.shape[1]} columns.")

There are 107 rows and 4 columns.

In [80]:
# What are the data types?
mammals.dtypes

weight      float64
speed       float64
hoppers        bool
specials       bool
dtype: object

In [ ]:
# Summarize the dataframe with .info and .describe
mammals.info
mammals.describe

In [39]:
# What is the the weight of the fastest animal?
fastest_animal_weight = mammals.sort_values(by='speed', ascending=False).head(1)['weight']

In [43]:
fastest_animal_weight.iloc[0]

55.0

In [104]:
mammals.loc[53]['weight']

55.0

In [106]:
print(f"The fastest animal has the weight of {mammals.loc[53]['weight']}")

The fastest animal has the weight of 55.0

In [118]:
# What is the overal percentage of specials?
mammals[mammals['specials'] ==  True]

     weight  speed  hoppers  specials
10   3800.0   25.0    False      True
59     12.0   24.0    False      True
60     11.0   30.0    False      True
65      5.0   27.0    False      True
66      3.0   16.0    False      True
68     70.0   40.0    False      True
69     13.0   37.0    False      True
70      9.0    3.2    False      True
105     5.0    7.4    False      True
107     4.0    1.6    False      True

In [120]:
#boolean mask skimming out the mammals that have true in their specials column
len(mammals[mammals['specials'] ==  True])

10

In [121]:
#All the the animals. So the specials will be a percentage of this total.
len(mammals)

107

In [133]:
#10/107 essentially
special_percent = str(len(mammals[mammals['specials'] ==  True]) / len(mammals))

In [136]:
#Lets make a nice print statement.
print(f"The percentage of animals that are special is {special_percent[:5]}%.")

The percentage of animals that are special is 0.093%.

In [ ]:
# How many animals are hoppers that are above the median speed? What percentage is this?

In [139]:
#the mammals who are hoppers
mammals[mammals['hoppers'] == True]

     weight  speed  hoppers  specials
82    0.056   21.0     True     False
85    0.035   32.0     True     False
86    0.035   14.0     True     False
96    4.600   64.0     True     False
97    4.400   72.0     True     False
98    4.000   72.0     True     False
99    3.500   56.0     True     False
100   2.000   64.0     True     False
101   1.900   56.0     True     False
102   1.500   50.0     True     False
103   1.500   40.0     True     False

In [45]:
#This is the median of the speed column
#This is done by calling all rows with :, and then calling for just the speed column by its
#explicit index, hence the .loc method. This selection is a series, which has a median method.
type(mammals.loc[:,"speed"])
speed_median = mammals.loc[:,"speed"].median()

In [46]:
#This is a less comlext way of getting to the speed column. Argh....
mammals['speed'].median()
speed_median

48.0

In [153]:
#Animals that are faster than the median.
mammals[(mammals['speed'] > speed_median) & (mammals['hoppers'] == True)]

     weight  speed  hoppers  specials
96      4.6   64.0     True     False
97      4.4   72.0     True     False
98      4.0   72.0     True     False
99      3.5   56.0     True     False
100     2.0   64.0     True     False
101     1.9   56.0     True     False
102     1.5   50.0     True     False

In [49]:
print(f"{7/len(mammals)} is the percentage of hoppers who are faster than the median.")

0.06542056074766354 is the percentage of hoppers who are faster than the median.